### ISSUE TITLE
CSS, image links don't obey subURLs

### ISSUE THREAD

**Issue by nii236** [crakjie/hugo-base-theme#4]
If I set my base URL to `www.domain.com/someURL/`, all hell breaks loose! CSS styles and images can not load because they're expecting everything to be located at `www.domain.com`, not `www.domain.com/someURL/`.

**Comment by crakjie** [comment]
So base url should be use every where?

**Comment by nii236** [comment]
Ideally yes, using root url doesn't work if you're running off sub-urls

**Comment by crakjie** [comment]
Did you want to make a PR or do you want me to handle this later?

**Comment by nii236** [comment]
I'm new to how Hugo works, so I'll have to have a look at how everything fits together first and see if I can do it or not

**Comment by crakjie** [comment]
Close by #5
