### ISSUE TITLE
How do I change header image?

### ISSUE THREAD

**Issue by JohnBlood** [crakjie/hugo-base-theme#8]
I'm working on a landing page and I found your theme very useful. However, I'm having trouble figuring out how to change the header image on the top of the page (the picture with the laptop). How do I do that? I have limited knowledge of html and css.  Thanks.

**Comment by crakjie** [comment]
Are you talking about the favicon ?
You can replace the file favicon.ico, I don't know why it's not .icon maybe a typo.

**Comment by JohnBlood** [comment]
No, I meant the picture of the laptop underneath the Hugo logo. I found it in the theme folder at /static/img/desk.jpg
